import { createRoot } from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import '@fontsource/league-spartan/400.css'
import '@fontsource/league-spartan/500.css'
import '@fontsource/league-spartan/600.css'
import '@fontsource/league-spartan/700.css'
import '@fontsource/league-spartan/800.css'
import '@fontsource/league-spartan/900.css'
import '@fontsource/playfair-display/400.css'
import '@fontsource/playfair-display/500.css'
import '@fontsource/playfair-display/600.css'
import '@fontsource/playfair-display/700.css'

createRoot(document.getElementById("root")!).render(<App />);
